# Rectangle scaling

Below we will show how to use the mxcad plug-in to implement the rectangular scaling function in CAD drawings. In this function, the user selects the target entity and sets the size of the reference rectangle. The selected entity will be scaled on the X-axis according to the width of the reference rectangle, and scaled on the Y-axis according to the height of the reference rectangle.

## Function implementation

1. Select the target entity and consolidate it into a block

We can call [MxCADSelectionSet](../../../../api/classes/2d.MxCADSelectionSet.md#class-mxcadselectionset)  Select the entity that you want to scale. Passes the selected entity [McDbBlockTableRecord.appendAcDbEntity()](../../../../api/classes/2d.McDbBlockTableRecord.md#appendacdbentity) method is consolidated into blocks. And through the properties [McDbBlockTableRecord.origin](../../../../api/classes/2d.McDbBlockTableRecord.md#origin) Set the center point of the consolidated block object as the base point.

```ts
// Gets the entity that needs to be scaled
let ss = new MxCADSelectionSet();
if (!await ss.userSelect("Select the entity that you want the rectangle to scale:")) return;
if (ss.count() == 0) return;

// Consolidate the target entity into a block object
let mxcad = MxCpp.getCurrentMxCAD();
let blkTable = mxcad.getDatabase().getBlockTable();
let blkRecId = blkTable.add(new McDbBlockTableRecord());//Block record
let blkTableRecord: McDbBlockTableRecord = blkRecId.getMcDbBlockTableRecord() as any;
if (blkTableRecord == null) return;

ss.forEach(id => {
    const ent = id.getMcDbEntity();
    if (!ent) return;
    const ent_clone = ent.clone() as McDbEntity;
    blkTableRecord.appendAcDbEntity(ent_clone);
})

let blkRef = new McDbBlockReference();
blkRef.blockTableRecordId = blkRecId;
// Set the block base point by calculating the physical bounding box
const { ret, maxPt, minPt } = blkRef.getBoundingBox();
if (!ret) return;
const line = new McDbLine(minPt, maxPt);
const length = line.getLength().val;
blkTableRecord.origin = line.getPointAtDist(length / 2).val;
```

2. Set the size of the reference rectangle

We by calling [MxCADUiPrPoint](../../../../api/classes/2d.MxCADUiPrPoint.md) take the object to determine the reference rectangular two angular point, And according to the Angle point location it is concluded that the other two vertices, through [McDbPolyline](../../../../api/classes/2d.McDbPolyline.md) section of the line to dynamically draw a rectangle.

```ts
// 选择矩形的两个角点
const getPt1 = new MxCADUiPrPoint();
getPt1.setMessage("请指定矩形的角点1");
const pt1 = await getPt1.go();
if (!pt1) return;
const getPt2 = new MxCADUiPrPoint();
getPt2.setMessage("请指定矩形角点2");
getPt2.setUserDraw((pt, pw) => {
    let pl = new McDbPolyline();
    pl.addVertexAt(pt1);
    pl.addVertexAt(new McGePoint3d(pt1.x, pt.y));
    pl.addVertexAt(pt);
    pl.addVertexAt(new McGePoint3d(pt.x, pt1.y));
    pl.isClosed = true;
    pw.drawMcDbEntity(pl);
})
const pt2 = await getPt2.go();
if (!pt2) return;
```

3. Set the scaling factor and draw the scaled rectangle entity

In the above step, we can obtain the width and height of the reference rectangle, the size of the bounding box where all the selected entities are located, and we can obtain the scaling factor of the entities on the X and Y axes respectively according to the ratio between the two. And finally, Set the fast object based on the resulting scaling factor [McDbBlockReference.scaleFactors](../../../../api/classes/2d.McDbBlockReference.md#scalefactor s) property and draw the scaled entity.

In the following example, we set the scaled entity position to the center point of the reference rectangle. In addition, We can also through [MxCADUiPrPoint](../../../../api/classes/2d.MxCADUiPrPoint.md) take object to dynamically set the position of the object.

```ts
// Calculated scaling factor
const scaleX = Math.abs(pt1.x - pt2.x) / Math.abs(minPt.x - maxPt.x);
const scaleY = Math.abs(pt1.y - pt2.y) / Math.abs(minPt.y - maxPt.y);
blkRef.scaleFactors = new McGePoint3d(scaleX, scaleY, 0);
const l = new McDbLine(pt1, pt2);
blkRef.position = l.getPointAtDist(l.getLength().val / 2).val;
// Draw object
mxcad.drawEntity(blkRef);
```

## Functional practice

Practical effects are as follows:
* Click the Rectangle Zoom button to perform the rectangle zoom method
* Left click to select the target entity, right click to end the selection
* Follow the command line prompts to set reference rectangle corners
* Successfully draws the entity after scaling the rectangle

:::demo
```tsx
import { MxFun } from "mxdraw"
import {  McObject, MxCADUiPrPoint, McDbLine, MxCADSelectionSet,McDbBlockTableRecord,
          McGePoint3d,McDbEntity, McDbBlockReference,  McDbPolyline } from "mxcad"

export default () => {
    const mxcad = new McObject()
    mxcad.create({
      canvas: "#myCanvas",
      locateFile: (fileName: string)=> {
            // CDN loading must use wasm/ 2D-ST resources, because github restrictions cannot use wasm/2d resources
            // wasm/2d must comply with the browser same-origin policy or use other means to circumvent the browser same-origin policy
            return self.location.origin + "/mxcad_docs/wasm/2d-st/" + fileName
      },
      // The directory location where the font is loaded
      fontspath: self.location.origin + "/mxcad_docs/fonts",
      // Load the converted drawing file
      fileUrl: self.location.origin + "/mxcad_docs/test4.mxweb",
      onOpenFileComplete:(mxcad)=>{
        mxcad.zoomW(new McGePoint3d(950,1200,0), new McGePoint3d(1100,1030,0))
        const cmdWindow: any = document.getElementById("myArea")

        // Displays command line message changes
        MxFun.listenForCommandLineInput(({
            msCmdTip,
            msCmdDisplay,
        }) => {
            cmdWindow.value = msCmdDisplay + "\n" + msCmdTip
            cmdWindow.scrollTop = cmdWindow.scrollHeight
        })
      }
    });
    // Rectangular scaling
    /**
     * Consolidates the selected entities into blocks
     * Set the scaling factor based on the size of the rectangle
     */
    async function Mx_RectangularScaling() {
        // Gets the entity that needs to be scaled
        let ss = new MxCADSelectionSet();
        if (!await ss.userSelect("请选择需要矩形缩放的实体:")) return;
        if (ss.count() == 0) return;

        // Consolidate the target entity into a block object
        let blkTable = mxcad.getDatabase().getBlockTable();
        let blkRecId = blkTable.add(new McDbBlockTableRecord());//Block record
        let blkTableRecord: McDbBlockTableRecord = blkRecId.getMcDbBlockTableRecord() as any;
        if (blkTableRecord == null) return;

        ss.forEach(id => {
            const ent = id.getMcDbEntity();
            if (!ent) return;
            const ent_clone = ent.clone() as McDbEntity;
            blkTableRecord.appendAcDbEntity(ent_clone);
        })

        let blkRef = new McDbBlockReference();
        blkRef.blockTableRecordId = blkRecId;
        // Set the block base point by calculating the physical bounding box
        const { ret, maxPt, minPt } = blkRef.getBoundingBox();
        if (!ret) return;
        const line = new McDbLine(minPt, maxPt);
        const length = line.getLength().val;
        blkTableRecord.origin = line.getPointAtDist(length / 2).val;

        // Select the two corner points of the rectangle
        const getPt1 = new MxCADUiPrPoint();
        getPt1.setMessage("Specify corner point 1 of the rectangle");
        const pt1 = await getPt1.go();
        if (!pt1) return;
        const getPt2 = new MxCADUiPrPoint();
        getPt2.setMessage("Please specify rectangle corner point 2");
        getPt2.setUserDraw((pt, pw) => {
            let pl = new McDbPolyline();
            pl.addVertexAt(pt1);
            pl.addVertexAt(new McGePoint3d(pt1.x, pt.y));
            pl.addVertexAt(pt);
            pl.addVertexAt(new McGePoint3d(pt.x, pt1.y));
            pl.isClosed = true;
            pw.drawMcDbEntity(pl);
        })
        const pt2 = await getPt2.go();
        if (!pt2) return;

        // Calculated scaling factor
        const scaleX = Math.abs(pt1.x - pt2.x) / Math.abs(minPt.x - maxPt.x);
        const scaleY = Math.abs(pt1.y - pt2.y) / Math.abs(minPt.y - maxPt.y);
        blkRef.scaleFactors = new McGePoint3d(scaleX, scaleY, 0);
        const l = new McDbLine(pt1, pt2);
        blkRef.position = l.getPointAtDist(l.getLength().val / 2).val;
        mxcad.drawEntity(blkRef);
    }
    return (<div style="height: 600px; overflow: hidden;">
      <button style="height:30px;border:1px solid #ccc;padding:0px 5px;margin-bottom:10px"
      id="myBtn" onClick={()=>Mx_RectangularScaling()}>Rectangular scaling</button>
      <div style="height: 450px;"><canvas id="myCanvas"></canvas></div>
      <div style="width: 100%;height: 150px;margin:10px 0px">
        <textarea style="width: 100%;height: 100px;background-color: #000;color: #fff;border-radius: 5px" id="myArea" readonly="true"></textarea>
      </div>
    </div>)
}
```
:::



