# Rotate

Below we will show how to use the mxcad plug-in to implement the rotation function in CAD drawings. In this function, the user can box select or click the target entity to rotate it for editing the content of the drawing. In our document [Common Editing operations](../../../5.图纸编辑/2.常用编辑操作.md#旋转) has done a basic explanation of the rotation operation, the following we will achieve the rotation function that can interact with users on this basis.

## Function implementation

1. Select the target entity

We can call [MxCADSelectionSet](../../../../api/classes/2d.MxCADSelectionSet.md#class-mxcadselectionset)  Select the entity that you want to rotate.

```ts
// Select the object you want to mirror
let ss = new MxCADSelectionSet();
if (!await ss.userSelect("\n Select the rotate object")) return;
```

2. Set the rotation Angle

We by calling [MxCADUiPrPoint](../../../../api/classes/2d.MxCADUiPrPoint.md) take the object to determine the rotation of the object points. Call again [MxCADUiPrAngle](../../../../api/classes/2d.MxCADUiPrAngle.md) for users to set of object rotation Angle. During the setup process, We can go through [MxCADUiPrAngle.setUserDraw()](../../../../api/classes/2d.MxCADUiPrPoint.md#setuserdraw)  Dynamically drawing the image object enables us to see the position of the rotated object more intuitively. Since the redrawing function needs to be continuously performed during the dynamic drawing process, in order to improve the rendering speed and reduce the drawing problem caused by too many rotating objects, We can temporarily consolidate the target object into a block [McDbBlockTableRecord](../../../../api/classes/2d.McDbBlockTableRecord.md), In the process of dynamic rendering, the initial rotation is carried out in the form of image blocks, and the target object is rotated after the final rotation Angle is determined.

```ts
// Set block
let blkTable =  mxcad.getDatabase().getBlockTable();
let blkRecId = blkTable.add(new McDbBlockTableRecord());
let blkTableRecord:McDbBlockTableRecord = blkRecId.getMcDbBlockTableRecord() as any;
if(blkTableRecord == null) return;
ss.forEach((id)=>{
    let ent = id.getMcDbEntity();
    if(!ent) return;
    let cent = ent.clone() as McDbEntity;
    blkTableRecord.appendAcDbEntity(cent);
})
// Set the block base point
blkTableRecord.origin = basePt;
let blkRef = new McDbBlockReference();
blkRef.blockTableRecordId = blkRecId;
// Set the block position
blkRef.position = basePt;


// Specified rotation Angle
let getAngle = new MxCADUiPrAngle();
getAngle.setMessage('Please specify the rotation Angle')
getAngle.setBasePt(basePt);
getAngle.setUserDraw((pt, pw) => {
    pw.drawLine(pt.toVector3(), basePt.toVector3());
    // Dynamically rotate the block
    let a = pt.sub(basePt).angleTo2(McGeVector3d.kXAxis, McGeVector3d.kNegateZAxis);
    const _clone = blkRef.clone() as McDbBlockReference;
    _clone.rotation = a;
    pw.drawMcDbEntity(_clone)
})
let val = await getAngle.go();
if (!val) return;
const angle = getAngle.value();
```

3. Rotate the object

In the above step, we obtained the rotation Angle, so, We can direct call [McDbEntity.rotate()](../../../../api/classes/2d.McDbEntity.md#rotate) method to rotate the object. After moving, Call [McObject.updateDisplay()](../../../../api/classes/2d.McObject.md#updatedisplay) method to update the drawing shows.

```ts
const mxcad = MxCpp.getCurrentMxCAD();
// Mirror image rotating entity
ss.forEach(id => {
    let ent = id.getMcDbEntity();
    if (!ent) return;
    ent.rotate(basePt, angle);
})
// Update display
mxcad.updateDisplay();
```

## Functional practice

Practical effects are as follows:
* Click the rotation button to perform the rotation method
* Left click to select the target entity, right click to end the selection (or direct box selection)
* Click the left button to set the rotation point according to the command line prompt
* Move the mouse and click the left button again to set the rotation Angle (or enter the Angle value directly in the input box and press Enter)
* Successfully rotated the object

:::demo
```tsx
import { MxFun } from "mxdraw"
import {  McObject, MxCADUiPrPoint, MxCADSelectionSet, McGePoint3d,McDbEntity, McDbBlockTableRecord,
          McDbBlockReference, MxCADUiPrAngle, McGeVector3d} from "mxcad"

export default () => {
    const mxcad = new McObject()
    mxcad.create({
      canvas: "#myCanvas",
      locateFile: (fileName: string)=> {
            // CDN loading must use wasm/ 2D-ST resources, because github restrictions cannot use wasm/2d resources
            // wasm/2d must comply with the browser same-origin policy or use other means to circumvent the browser same-origin policy
            return self.location.origin + "/mxcad_docs/wasm/2d-st/" + fileName
      },
      // The directory location where the font is loaded
      fontspath: self.location.origin + "/mxcad_docs/fonts",
      // Load the converted drawing file
      fileUrl: self.location.origin + "/mxcad_docs/test4.mxweb",
      onOpenFileComplete:(mxcad)=>{
        mxcad.zoomW(new McGePoint3d(740, 1390, 0), new McGePoint3d(1060, 1265, 0));
        const inputBox: any = document.getElementById("myInput")
        const cmdWindow: any = document.getElementById("myArea")

        // Listen for command line input
        let inputText = ""
        inputBox.oninput = () => {
            inputText = inputBox.value
        }
        inputBox.onkeydown = (e) => {
            MxFun.setCommandLineInputData(inputText, e.keyCode)
            if (e.keyCode === 13) inputText = inputBox.value = ""
        }

        // Displays command line message changes
        MxFun.listenForCommandLineInput(({
            msCmdTip,
            msCmdDisplay,
        }) => {
            cmdWindow.value = msCmdDisplay + "\n" + msCmdTip
            cmdWindow.scrollTop = cmdWindow.scrollHeight
        })
      }
    });
    // rotate
    async function Mx_Rotation() {
        // Select copy object
        let ss = new MxCADSelectionSet();
        if (!await ss.userSelect("Select Copy rotation object:")) return;
        if (ss.count() == 0) return;
        const getBasePt = new MxCADUiPrPoint();
        getBasePt.setMessage('Specified rotation base');
        const basePt = await getBasePt.go();

        let blkTable =  mxcad.getDatabase().getBlockTable();
        let blkRecId = blkTable.add(new McDbBlockTableRecord());
        let blkTableRecord:McDbBlockTableRecord = blkRecId.getMcDbBlockTableRecord() as any;
        if(blkTableRecord == null) return;
        ss.forEach((id)=>{
        let ent = id.getMcDbEntity();
        if(!ent) return;
        let cent = ent.clone() as McDbEntity;
        blkTableRecord.appendAcDbEntity(cent);
        })
        blkTableRecord.origin = basePt;

        let blkRef = new McDbBlockReference();
        blkRef.blockTableRecordId = blkRecId;
        blkRef.position = basePt;
    

        // Specified rotation Angle
        let getAngle = new MxCADUiPrAngle();
        getAngle.setMessage('Please specify the rotation Angle')
        getAngle.setBasePt(basePt);
        getAngle.setUserDraw((pt, pw) => {
            pw.drawLine(pt.toVector3(), basePt.toVector3());
            let a = pt.sub(basePt).angleTo2(McGeVector3d.kXAxis, McGeVector3d.kNegateZAxis);
            const _clone = blkRef.clone() as McDbBlockReference;
            _clone.rotation = a;
            pw.drawMcDbEntity(_clone)
        })
        let val = await getAngle.go();
        if (!val) return;
        const angle = getAngle.value();
        ss.forEach(id => {
            let ent = id.getMcDbEntity();
            if (!ent) return;
            let event_clone = ent.clone() as McDbEntity;
            event_clone.rotate(basePt, angle)
            mxcad.drawEntity(event_clone);
            ent.erase();
        })
    }
    return (<div style="height: 650px; overflow: hidden;">
      <button style="height:30px;border:1px solid #ccc;padding:0px 5px;margin-bottom:10px"
      id="myBtn" onClick={()=>Mx_Rotation()}>rotate</button>
      <div style="height: 450px;"><canvas id="myCanvas"></canvas></div>
      <div style="width: 100%;height: 150px;margin:10px 0px">
        <textarea style="width: 100%;height: 100px;background-color: #000;color: #fff;border-radius: 5px" id="myArea" readonly="true"></textarea>
        <input style="width:100%;height:30px;background-color: #000;color: #fff;" id="myInput"/>
      </div>
    </div>)
}
```
:::



