[mxcad_2d API 文档](../README.md) / [2d](../modules/2d.md) / McDbAttribute

# Class: McDbAttribute

[2d](../modules/2d.md).McDbAttribute

块引用中的属性定义文字类

**`Example`**

```ts 
   import { McDbBlockReference, McDbAttribute } from "mxcad"

   // 遍历块中的属性文字 ent:块实体
   let blkRef: McDbBlockReference = ent;
   let aryId = blkRef.getAllAttribute();
   aryId.forEach((id) => {
       let attribt: McDbAttribute = id.getMcDbEntity() as any;
       console.log(attribt.textString);
       console.log(attribt.tag);
   })
```
```ts
   // 在块中插入属性文字 ent:块实体
   let blkRef: McDbBlockReference = ent;
   const blkrecId = blkRef.blockTableRecordId; // 获取块表记录id
   let blkRecord: any = blkrecId.getMcDbBlockTableRecord();// 获取块表记录对象
   let ids = blkRecord.getAllEntityId(); // 获取块表记录中所有实例对象ID
   ids.forEach((id: any, index: any) => {
       // 筛选 McDbAttributeDefinition 对象
       if (!id.isKindOf("McDbAttributeDefinition")) return;
       let attribDef = id.getMcDbEntity() as McDbAttributeDefinition;
       let tag = attribDef.tag; // 获取属性标签
       let txt = attribDef.textString; // 获取文字的字符串

       let attrib = new McDbAttribute(); // 构造新属性定义文字对象
       attrib.position = attribDef.position; // 设置对象位置
       attrib.alignmentPoint = attribDef.alignmentPoint // 设置对象对齐位置
       attrib.height = attribDef.height ; // 设置对象字高
       attrib.trueColor = attribDef.trueColor // 设置对象颜色
       attrib.widthFactor = attribDef.widthFactor; // 设置对象宽度因子
       // 设置文字的字符串
       if (txt.length > 0) attrib.textString = txt; 
       else attrib.textString = "test" + index;
       attrib.tag = tag;// 设置属性标签
       attrib.isInvisible = attribDef.isInvisible;
       attrib.transformBy(blkRef.blockTransform); // 块转换
       attrib = blkRef.appendAttribute(attrib).getMcDbEntity() as McDbAttribute;
       attrib.textStyle = attribDef.textStyle
       attrib.layer = attribDef.layer
   })
```

## Hierarchy

- [`McDbText`](2d.McDbText.md)

  ↳ **`McDbAttribute`**

## Table of contents

### Constructors

- [constructor](2d.McDbAttribute.md#constructor)

### Properties

- [imp](2d.McDbAttribute.md#imp)

### Accessors

- [alignmentPoint](2d.McDbAttribute.md#alignmentpoint)
- [colorIndex](2d.McDbAttribute.md#colorindex)
- [drawOrder](2d.McDbAttribute.md#draworder)
- [dxf0](2d.McDbAttribute.md#dxf0)
- [height](2d.McDbAttribute.md#height)
- [horizontalMode](2d.McDbAttribute.md#horizontalmode)
- [isInvisible](2d.McDbAttribute.md#isinvisible)
- [layer](2d.McDbAttribute.md#layer)
- [layerId](2d.McDbAttribute.md#layerid)
- [linetype](2d.McDbAttribute.md#linetype)
- [linetypeId](2d.McDbAttribute.md#linetypeid)
- [linetypeScale](2d.McDbAttribute.md#linetypescale)
- [lineweight](2d.McDbAttribute.md#lineweight)
- [normal](2d.McDbAttribute.md#normal)
- [objectName](2d.McDbAttribute.md#objectname)
- [oblique](2d.McDbAttribute.md#oblique)
- [position](2d.McDbAttribute.md#position)
- [rotation](2d.McDbAttribute.md#rotation)
- [tag](2d.McDbAttribute.md#tag)
- [textString](2d.McDbAttribute.md#textstring)
- [textStyle](2d.McDbAttribute.md#textstyle)
- [textStyleId](2d.McDbAttribute.md#textstyleid)
- [trueColor](2d.McDbAttribute.md#truecolor)
- [verticalMode](2d.McDbAttribute.md#verticalmode)
- [visible](2d.McDbAttribute.md#visible)
- [widthFactor](2d.McDbAttribute.md#widthfactor)

### Methods

- [IntersectWith](2d.McDbAttribute.md#intersectwith)
- [assertObjectModification](2d.McDbAttribute.md#assertobjectmodification)
- [clone](2d.McDbAttribute.md#clone)
- [createExtensionDictionary](2d.McDbAttribute.md#createextensiondictionary)
- [deleteXData](2d.McDbAttribute.md#deletexdata)
- [disableDisplay](2d.McDbAttribute.md#disabledisplay)
- [erase](2d.McDbAttribute.md#erase)
- [explode](2d.McDbAttribute.md#explode)
- [getAllAppName](2d.McDbAttribute.md#getallappname)
- [getArea](2d.McDbAttribute.md#getarea)
- [getBoundingBox](2d.McDbAttribute.md#getboundingbox)
- [getDatabase](2d.McDbAttribute.md#getdatabase)
- [getDatabaseIndexId](2d.McDbAttribute.md#getdatabaseindexid)
- [getExtensionDictionary](2d.McDbAttribute.md#getextensiondictionary)
- [getGripPoints](2d.McDbAttribute.md#getgrippoints)
- [getHandle](2d.McDbAttribute.md#gethandle)
- [getImp](2d.McDbAttribute.md#getimp)
- [getJson](2d.McDbAttribute.md#getjson)
- [getObjectID](2d.McDbAttribute.md#getobjectid)
- [getOwnerID](2d.McDbAttribute.md#getownerid)
- [getxData](2d.McDbAttribute.md#getxdata)
- [getxDataDouble](2d.McDbAttribute.md#getxdatadouble)
- [getxDataLong](2d.McDbAttribute.md#getxdatalong)
- [getxDataPoint](2d.McDbAttribute.md#getxdatapoint)
- [getxDataString](2d.McDbAttribute.md#getxdatastring)
- [highlight](2d.McDbAttribute.md#highlight)
- [initTempObject](2d.McDbAttribute.md#inittempobject)
- [isErased](2d.McDbAttribute.md#iserased)
- [isHaveExtensionDictionary](2d.McDbAttribute.md#ishaveextensiondictionary)
- [isKindOf](2d.McDbAttribute.md#iskindof)
- [isNull](2d.McDbAttribute.md#isnull)
- [mirror](2d.McDbAttribute.md#mirror)
- [move](2d.McDbAttribute.md#move)
- [moveGripPointsAt](2d.McDbAttribute.md#movegrippointsat)
- [rotate](2d.McDbAttribute.md#rotate)
- [scaleEntity](2d.McDbAttribute.md#scaleentity)
- [setJson](2d.McDbAttribute.md#setjson)
- [setxData](2d.McDbAttribute.md#setxdata)
- [setxDataDouble](2d.McDbAttribute.md#setxdatadouble)
- [setxDataLong](2d.McDbAttribute.md#setxdatalong)
- [setxDataPoint](2d.McDbAttribute.md#setxdatapoint)
- [setxDataString](2d.McDbAttribute.md#setxdatastring)
- [syncData](2d.McDbAttribute.md#syncdata)
- [transformBy](2d.McDbAttribute.md#transformby)
- [unErase](2d.McDbAttribute.md#unerase)
- [updateDisplay](2d.McDbAttribute.md#updatedisplay)

## Constructors

### constructor

• **new McDbAttribute**(`imp?`)

构造函数。

**`Example`**

```ts
import { McDbAttribute } from "mxcad";

const attrib = new McDbAttribute();
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `imp?` | `any` | 实现对象。 |

#### Overrides

[McDbText](2d.McDbText.md).[constructor](2d.McDbText.md#constructor)

## Properties

### imp

• **imp**: `any` = `0`

内部实现对象。

#### Inherited from

[McDbText](2d.McDbText.md).[imp](2d.McDbText.md#imp)

## Accessors

### alignmentPoint

• `get` **alignmentPoint**(): [`McGePoint3d`](2d.McGePoint3d.md)

获取文字的对齐点。

**`Example`**

```ts
// 假设text为有效文本实体
const alignmentPoint = text.alignmentPoint;
```

#### Returns

[`McGePoint3d`](2d.McGePoint3d.md)

#### Inherited from

McDbText.alignmentPoint

• `set` **alignmentPoint**(`pt`): `void`

设置文字的对齐点。

**`Example`**

```ts
import { McDbText, McGePoint3d } from "mxcad";

const text = new McDbText();
text.alignmentPoint = new McGePoint3d(0,0,0);
console.log(text.alignmentPoint)//(0,0,0)
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `pt` | [`McGePoint3d`](2d.McGePoint3d.md) | 三维点向量 |

#### Returns

`void`

#### Inherited from

McDbText.alignmentPoint

___

### colorIndex

• `get` **colorIndex**(): `number`

得到对象颜色索引

**`Example`**

```ts
 import { McDbEntity, ColorIndexType } from 'mxcad'
 const ent = new McDbEntity();
 ent.colorIndex = ColorIndexType.kByblock;
 console.log(ent.colorIndex)
```

#### Returns

`number`

#### Inherited from

McDbText.colorIndex

• `set` **colorIndex**(`val`): `void`

设置对象颜色索引

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | `number` | 颜色索引（ColorIndexType） |

#### Returns

`void`

#### Inherited from

McDbText.colorIndex

___

### drawOrder

• `get` **drawOrder**(): `number`

对象的显示顺序

**`Example`**

```ts
// 假设ent为有效实例对象
const order = ent.drawOrder();
```

#### Returns

`number`

#### Inherited from

McDbText.drawOrder

• `set` **drawOrder**(`order`): `void`

对象的显示顺序

**`Example`**

```ts
import { MxCpp, MxCADSelectionSet } from "mxcad";

let ss = new MxCADSelectionSet();
if (!await ss.userSelect("\n选择对象")) return;
//得到当前图上对象的最大，小最显示顺序.
let minmaxOrder = MxCpp.getCurrentDatabase().currentSpace.getMinMaxDrawOrder();
// 把对象放到最上面。
let lOrder = minmaxOrder.maxDrawOrder + 1;
ss.forEach((id) => {
  let ent = id.getMcDbEntity();
  if (ent) {
    ent.drawOrder = lOrder;
  }
})
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `order` | `number` | 顺序值 |

#### Returns

`void`

#### Inherited from

McDbText.drawOrder

___

### dxf0

• `get` **dxf0**(): `string`

得到对象的DXF组码的类型名，这个和AutoCAD中的DXF组码是一样。
比如直线的类型名为：McDbLine，DXF0组码值: LINE,DXF0组码值可以用来构造集时的类型过滤。

#### Returns

`string`

#### Inherited from

McDbText.dxf0

___

### height

• `get` **height**(): `number`

获取文字的高度。

**`Example`**

```ts
// 假设text为有效文本实体
const height = text.height;
```

#### Returns

`number`

#### Inherited from

McDbText.height

• `set` **height**(`val`): `void`

设置文字高度

**`Example`**

```ts
import { McDbText } from "mxcad";

const text = new McDbText();
text.height = 20;
console.log(text.height)//20
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | `number` | 高度 |

#### Returns

`void`

#### Inherited from

McDbText.height

___

### horizontalMode

• `get` **horizontalMode**(): [`TextHorzMode`](../enums/2d.McDb.TextHorzMode.md)

获取文字的水平对齐方式。

**`Example`**

```ts
// 假设text为有效文本实体
const horizontalMode = text.horizontalMode;
```

#### Returns

[`TextHorzMode`](../enums/2d.McDb.TextHorzMode.md)

#### Inherited from

McDbText.horizontalMode

• `set` **horizontalMode**(`val`): `void`

设置文字的水平对齐方式。

**`Example`**

```ts
import { McDbText, McDb } from "mxcad";

const text = new McDbText();
text.horizontalMode = McDb.TextHorzMode.kTextAlign;
console.log(text.horizontalMode)//3
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | [`TextHorzMode`](../enums/2d.McDb.TextHorzMode.md) | 文字水平对齐方式 |

#### Returns

`void`

#### Inherited from

McDbText.horizontalMode

___

### isInvisible

• `get` **isInvisible**(): `boolean`

获取块属性文字是否可见

**`Example`**

```ts
import { McDbAttribute } from "mxcad";

const attrib = new McDbAttribute();
const isV = attrib.isInvisible;
if(isV){
  //属性可见
}else{
  //属性不可见
}
```

#### Returns

`boolean`

• `set` **isInvisible**(`val`): `void`

设置块属性文字是否不可见

**`Example`**

```ts
import { McDbAttribute } from "mxcad";

const attrib = new McDbAttribute();
attrib.isInvisible = false;// 设置属性可见
attrib.isInvisible = true;// 设置属性不可见

#### Parameters

| Name | Type |
| :------ | :------ |
| `val` | `boolean` |

#### Returns

`void`

___

### layer

• `get` **layer**(): `string`

得到对象图层名

#### Returns

`string`

#### Inherited from

McDbText.layer

• `set` **layer**(`val`): `void`

设置对象图层名

**`Example`**

```ts
 import { McDbEntity } from 'mxcad'
 const ent = new McDbEntity();
 ent.layer = "newLayerName";
 console.log(ent.layer)
 ```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | `string` | 图层名 |

#### Returns

`void`

#### Inherited from

McDbText.layer

___

### layerId

• `get` **layerId**(): [`McObjectId`](2d.McObjectId.md)

获取图层ID对象

**`Example`**

```ts
// 假设ent为有效实例对象
const layerId = ent.layerId;
```

#### Returns

[`McObjectId`](2d.McObjectId.md)

#### Inherited from

McDbText.layerId

• `set` **layerId**(`id`): `void`

设置图层Id对象

**`Example`**

```ts
// 假设ent为有效实例对象
const mxcad = MxCpp.getCurrentMxCAD();
const layerId = mxcad.addLayer("测试图层")
ent.layerId = layerId;
```

#### Parameters

| Name | Type |
| :------ | :------ |
| `id` | [`McObjectId`](2d.McObjectId.md) |

#### Returns

`void`

#### Inherited from

McDbText.layerId

___

### linetype

• `get` **linetype**(): `string`

得到对象线型名

#### Returns

`string`

#### Inherited from

McDbText.linetype

• `set` **linetype**(`val`): `void`

设置对象线型名

**`Example`**

```ts
import { McDbEntity } from 'mxcad'
const ent = new McDbEntity()
ent.linetype = "MyLineType";
console.log(ent.linetype)
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | `string` | 线型名 |

#### Returns

`void`

#### Inherited from

McDbText.linetype

___

### linetypeId

• `get` **linetypeId**(): [`McObjectId`](2d.McObjectId.md)

获取实体对象线型ID

**`Example`**

```ts
// 假设ent为有效实例对象
const linetypeId = ent.linetypeId;
```

#### Returns

[`McObjectId`](2d.McObjectId.md)

#### Inherited from

McDbText.linetypeId

• `set` **linetypeId**(`id`): `void`

设置实体对象线型ID

**`Example`**

```ts
// 假设ent为有效实例对象
const mxcad = MxCpp.getCurrentMxCAD();
const lineId = mxcad.addLinetypeEx("TestMyLine", '25,-5');
ent.linetypeId = lineId;
```

#### Parameters

| Name | Type |
| :------ | :------ |
| `id` | [`McObjectId`](2d.McObjectId.md) |

#### Returns

`void`

#### Inherited from

McDbText.linetypeId

___

### linetypeScale

• `get` **linetypeScale**(): `number`

得到对象线型比例

#### Returns

`number`

#### Inherited from

McDbText.linetypeScale

• `set` **linetypeScale**(`val`): `void`

设置对象线型比例

**`Example`**

```ts
import { McDbEntity } from 'mxcad'
const ent = new McDbEntity()
ent.linetypeScale = 0.8;
console.log(ent.linetypeScale)
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | `number` | 线型比例 |

#### Returns

`void`

#### Inherited from

McDbText.linetypeScale

___

### lineweight

• `get` **lineweight**(): `number`

得到对象线重

#### Returns

`number`

#### Inherited from

McDbText.lineweight

• `set` **lineweight**(`val`): `void`

设置对象线重

**`Example`**

```ts
import { McDbEntity } from 'mxcad'
const ent = new McDbEntity()
ent.lineweight = 20;
console.log(ent.lineweight)
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | `number` | 线重 |

#### Returns

`void`

#### Inherited from

McDbText.lineweight

___

### normal

• `get` **normal**(): [`McGeVector3d`](2d.McGeVector3d.md)

返回对象的normal

**`Example`**

```ts
```

#### Returns

[`McGeVector3d`](2d.McGeVector3d.md)

#### Inherited from

McDbText.normal

• `set` **normal**(`val`): `void`

设置对象的normal

**`Example`**

```ts
```

#### Parameters

| Name | Type |
| :------ | :------ |
| `val` | [`McGeVector3d`](2d.McGeVector3d.md) |

#### Returns

`void`

#### Inherited from

McDbText.normal

___

### objectName

• `get` **objectName**(): `string`

获取对象名称。

**`Example`**

```ts
import { McRxObject } from 'mxcad';

let obj = new McRxObject();
console.log(obj.objectName);
```

#### Returns

`string`

返回对象名

#### Inherited from

McDbText.objectName

___

### oblique

• `get` **oblique**(): `number`

获取文字的倾斜角度。

**`Example`**

```ts
// 假设text为有效文本实体
const oblique = text.oblique;
```

#### Returns

`number`

#### Inherited from

McDbText.oblique

• `set` **oblique**(`val`): `void`

设置文字的倾斜角度。

**`Example`**

```ts
import { McDbText } from "mxcad";

const text = new McDbText();
text.oblique = Math.PI/4;
console.log(text.oblique)//45
```

#### Parameters

| Name | Type |
| :------ | :------ |
| `val` | `number` |

#### Returns

`void`

#### Inherited from

McDbText.oblique

___

### position

• `get` **position**(): [`McGePoint3d`](2d.McGePoint3d.md)

获取文字的位置。

**`Example`**

```ts
// 假设text为有效文本实体
const position = text.position;
```

#### Returns

[`McGePoint3d`](2d.McGePoint3d.md)

#### Inherited from

McDbText.position

• `set` **position**(`pt`): `void`

设置文字的位置。

**`Example`**

```ts
import { McDbText, McGePoint3d } from "mxcad";

const text = new McDbText();
text.position = new McGePoint3d(0,0,0);
console.log(text.position)//(0,0,0)
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `pt` | [`McGePoint3d`](2d.McGePoint3d.md) | 三维点向量 |

#### Returns

`void`

#### Inherited from

McDbText.position

___

### rotation

• `get` **rotation**(): `number`

获取文字的旋转角度。

**`Example`**

```ts
// 假设text为有效文本实体
const rotation = text.rotation;
```

#### Returns

`number`

#### Inherited from

McDbText.rotation

• `set` **rotation**(`pt`): `void`

设置文字的旋转角度。

**`Example`**

```ts
import { McDbText } from "mxcad";

const text = new McDbText();
text.rotation = Math.PI/4;
console.log(text.rotation)//45
```

#### Parameters

| Name | Type |
| :------ | :------ |
| `pt` | `number` |

#### Returns

`void`

#### Inherited from

McDbText.rotation

___

### tag

• `get` **tag**(): `string`

获取文字的字符串。

**`Example`**

```ts
import { McDbAttribute } from "mxcad";

const attrib = new McDbAttribute();
const tag = attrib.tag;
```

#### Returns

`string`

• `set` **tag**(`val`): `void`

设置文字的字符串。

**`Example`**

```ts
import { McDbAttribute } from "mxcad";

const attrib = new McDbAttribute();
attrib.tag = "example_tag"
```

#### Parameters

| Name | Type |
| :------ | :------ |
| `val` | `string` |

#### Returns

`void`

___

### textString

• `get` **textString**(): `string`

获取文字的字符串。

**`Example`**

```ts
// 假设text为有效文本实体
const textString = text.textString;
```

#### Returns

`string`

#### Inherited from

McDbText.textString

• `set` **textString**(`val`): `void`

设置文字的字符串。

**`Example`**

```ts
import { McDbText } from "mxcad";

const text = new McDbText();
text.textString = "测试文本";
console.log(text.textString)//测试文本
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | `string` | 字符串 |

#### Returns

`void`

#### Inherited from

McDbText.textString

___

### textStyle

• `get` **textStyle**(): `string`

得到对象文字样式

#### Returns

`string`

#### Inherited from

McDbText.textStyle

• `set` **textStyle**(`val`): `void`

设置对象文字样式

**`Example`**

```ts
import { McDbEntity } from 'mxcad'
const ent = new McDbEntity()
ent.textStyle = "st_style";
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | `string` | 文字样式名 |

#### Returns

`void`

#### Inherited from

McDbText.textStyle

___

### textStyleId

• `get` **textStyleId**(): [`McObjectId`](2d.McObjectId.md)

获取实体文字样式

**`Example`**

```ts
// 假设ent为有效实例对象
const textStyleId = ent.textStyleId;
```

#### Returns

[`McObjectId`](2d.McObjectId.md)

#### Inherited from

McDbText.textStyleId

• `set` **textStyleId**(`id`): `void`

设置实体的文字样式

**`Example`**

```ts
// 假设ent为有效实例对象
const mxcad = MxCpp.getCurrentMxCAD();
const textStyleId = mxcad.addTextStyle("MyLineTypeTextStyle", "txt.shx", "hztxt.shx", 1);
ent.textStyleId = textStyleId;
```

#### Parameters

| Name | Type |
| :------ | :------ |
| `id` | [`McObjectId`](2d.McObjectId.md) |

#### Returns

`void`

#### Inherited from

McDbText.textStyleId

___

### trueColor

• `get` **trueColor**(): [`McCmColor`](2d.McCmColor.md)

得到对象颜色

**`Example`**

```ts
 import { McDbEntity, McCmColor} from 'mxcad'
 const ent = new McDbEntity();
 ent.trueColor = new McCmColor(255, 0, 0);
 console.log(ent.trueColor)
```

#### Returns

[`McCmColor`](2d.McCmColor.md)

#### Inherited from

McDbText.trueColor

• `set` **trueColor**(`val`): `void`

设置对象颜色

#### Parameters

| Name | Type |
| :------ | :------ |
| `val` | [`McCmColor`](2d.McCmColor.md) |

#### Returns

`void`

#### Inherited from

McDbText.trueColor

___

### verticalMode

• `get` **verticalMode**(): [`TextVertMode`](../enums/2d.McDb.TextVertMode.md)

获取文字的垂直对齐方式。

**`Example`**

```ts
// 假设text为有效文本实体
const verticalMode = text.verticalMode;
```

#### Returns

[`TextVertMode`](../enums/2d.McDb.TextVertMode.md)

#### Inherited from

McDbText.verticalMode

• `set` **verticalMode**(`val`): `void`

设置文字的垂直对齐方式。

**`Example`**

```ts
import { McDbText, McDb } from "mxcad";

const text = new McDbText();
text.verticalMode = McDb.TextVertMode.kTextVertMid;
console.log(text.verticalMode)//2
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | [`TextVertMode`](../enums/2d.McDb.TextVertMode.md) | 文字垂直对齐方式 |

#### Returns

`void`

#### Inherited from

McDbText.verticalMode

___

### visible

• `get` **visible**(): `boolean`

对象是否可见

#### Returns

`boolean`

#### Inherited from

McDbText.visible

• `set` **visible**(`val`): `void`

设置是否可见

**`Example`**

```ts
import { McDbEntity } from 'mxcad'
const ent = new McDbEntity()
ent.visible = true;
console.log(ent.visible)
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | `boolean` | 布尔值 |

#### Returns

`void`

#### Inherited from

McDbText.visible

___

### widthFactor

• `get` **widthFactor**(): `number`

获取文字的宽度因子。

**`Example`**

```ts
// 假设text为有效文本实体
const widthFactor = text.widthFactor;
```

#### Returns

`number`

#### Inherited from

McDbText.widthFactor

• `set` **widthFactor**(`val`): `void`

设置文字的宽度因子。

**`Example`**

```ts
import { McDbText } from "mxcad";

const text = new McDbText();
text.height = 0.8;
console.log(text.height)//0.8
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `val` | `number` | 宽度因子 |

#### Returns

`void`

#### Inherited from

McDbText.widthFactor

## Methods

### IntersectWith

▸ **IntersectWith**(`intersectObject`, `exOption`): [`McGePoint3dArray`](2d.McGePoint3dArray.md)

与其他实体相交, 得到交点

**`Example`**

```ts
import { McDbLine, McDb } from 'mxcad'
const line1 = new McDbLine(new McGePoint3d(0,0,0), new McGePoint3d(20,1,0));
const line2 = new McDbLine(new McGePoint3d(10,10,0), new McGePoint3d(11,1,0));
const ptArr = line1.IntersectWith(line2, McDb.Intersect.kExtendBoth)
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `intersectObject` | [`McDbEntity`](2d.McDbEntity.md) | 需要相交的是实体对象 |
| `exOption` | [`Intersect`](../enums/2d.McDb.Intersect.md) | 相交的选项 |

#### Returns

[`McGePoint3dArray`](2d.McGePoint3dArray.md)

得到所有交点

#### Inherited from

[McDbText](2d.McDbText.md).[IntersectWith](2d.McDbText.md#intersectwith)

___

### assertObjectModification

▸ **assertObjectModification**(`autoUndo?`): `number`

设置对象被改变的状态，可自动触发更新显示函数，更新显示。
比如块表记录更新了，需要通知块引用更新显示，可以调用该函数。

**`Example`**

```ts
//假设obj为一个数据库对象
obj.assertObjectModification()
```

#### Parameters

| Name | Type | Default value |
| :------ | :------ | :------ |
| `autoUndo` | `boolean` | `false` |

#### Returns

`number`

#### Inherited from

[McDbText](2d.McDbText.md).[assertObjectModification](2d.McDbText.md#assertobjectmodification)

___

### clone

▸ **clone**(): ``null`` \| [`McDbObject`](2d.McDbObject.md)

克隆对象。

**`Example`**

```ts
//假设obj为一个数据库对象
const obj_clone = obj.clone();
```

#### Returns

``null`` \| [`McDbObject`](2d.McDbObject.md)

克隆出的对象。

#### Inherited from

[McDbText](2d.McDbText.md).[clone](2d.McDbText.md#clone)

___

### createExtensionDictionary

▸ **createExtensionDictionary**(): `boolean`

创建对象的扩展字典数据.

**`Example`**

```ts
//假设obj为一个数据库对象
const res = obj.createExtensionDictionary();
```

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[createExtensionDictionary](2d.McDbText.md#createextensiondictionary)

___

### deleteXData

▸ **deleteXData**(`appName`): `boolean`

删除实体指定应用程序名称相关的数据

**`Example`**

```ts
import { MxCADUiPrEntity, McDbEntity } from "mxcad";

let selEntity = new MxCADUiPrEntity();
selEntity.setMessage("选择对象");
let id = await selEntity.go();
if (!id.isValid()) return;
let ent:McDbEntity = id.getMcDbEntity();
if (ent === null) return;
const res = ent.deleteXData("DataName");
if(res){
  //删除成功
}else
  //删除失败
}
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `appName` | `string` | 扩展数据名称 |

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[deleteXData](2d.McDbText.md#deletexdata)

___

### disableDisplay

▸ **disableDisplay**(`isDisable`): `void`

禁用对象的自动更新显示.

**`Example`**

```ts
import { McDbLine } from 'mxcad'
const line1 = new McDbLine(new McGePoint3d(0,0,0), new McGePoint3d(20,1,0));
line1.disableDisplay(true)
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `isDisable` | `boolean` | 是否禁用对象自动更新显示 |

#### Returns

`void`

#### Inherited from

[McDbText](2d.McDbText.md).[disableDisplay](2d.McDbText.md#disabledisplay)

___

### erase

▸ **erase**(): `boolean`

删除对象。

**`Example`**

```ts
//假设obj为一个数据库对象
const res = obj.erase();
console.log(res);
```

#### Returns

`boolean`

是否删除成功。

#### Inherited from

[McDbText](2d.McDbText.md).[erase](2d.McDbText.md#erase)

___

### explode

▸ **explode**(): [`MxCADResbuf`](2d.MxCADResbuf.md)

打碎对象，返回打后对象数据链表

**`Example`**

```ts
import { McDbEntity, MxCADResbuf } from "mxcad";
// 获取目标对象
let getEnt = new MxCADUiPrEntity();
getEnt.setMessage("选择打碎对象:");
let id = await getEnt.go();
let ent:McDbEntity = id.getMcDbEntity();
if (ent === null) return;
// 打碎对象
      let retExplode: MxCADResbuf = ent.explode();
      if (retExplode.GetCount() == 0) return;
      let iExplodeConut = retExplode.GetCount();
      for (let j = 0; j < iExplodeConut; j++) {
          let tmpobj = retExplode.AtObject(j).val;
          if(tmpobj instanceof McDbEntity ){
              mxcad.drawEntity(tmpobj);
          }
      }
```

#### Returns

[`MxCADResbuf`](2d.MxCADResbuf.md)

resbuf 数据

#### Inherited from

[McDbText](2d.McDbText.md).[explode](2d.McDbText.md#explode)

___

### getAllAppName

▸ **getAllAppName**(): [`McGeStringArray`](2d.McGeStringArray.md)

获取实体中包含的所有 XData 记录的应用程序名（AppName）

**`Example`**

```ts
// 假设ent为有效实例对象
const appNames = ent.getAllAppName();
console.log(appNames);
```

#### Returns

[`McGeStringArray`](2d.McGeStringArray.md)

#### Inherited from

[McDbText](2d.McDbText.md).[getAllAppName](2d.McDbText.md#getallappname)

___

### getArea

▸ **getArea**(): `Object`

计算面积

**`Example`**

```ts
import { McGePoint3d, McDbCircle } from "mxcad"

const center = new McGePoint3d(0,0,0);
const circle = new McDbCircle(center, 20);
const area = circle.getArea();
console.log("圆面积：", area)
```

#### Returns

`Object`

val 面积值 | ret 是否获取成功

| Name | Type |
| :------ | :------ |
| `ret` | `boolean` |
| `val` | `number` |

#### Inherited from

[McDbText](2d.McDbText.md).[getArea](2d.McDbText.md#getarea)

___

### getBoundingBox

▸ **getBoundingBox**(): `Object`

得到对象的最小外包

**`Example`**

```ts
import { McDbText, McGePoint3d } from 'mxcad'
const text = new McDbText();
text.textString = "测试Test";
text.height = 20;
text.position = text.alignmentPoint = new McGePoint3d(0,0,0);
const { minPt, maxPt, ret } = text.getBoundingBox()
```

#### Returns

`Object`

| Name | Type |
| :------ | :------ |
| `maxPt` | [`McGePoint3d`](2d.McGePoint3d.md) |
| `minPt` | [`McGePoint3d`](2d.McGePoint3d.md) |
| `ret` | `boolean` |

#### Inherited from

[McDbText](2d.McDbText.md).[getBoundingBox](2d.McDbText.md#getboundingbox)

___

### getDatabase

▸ **getDatabase**(): [`McDbDatabase`](2d.McDbDatabase.md)

得到对象所在的数据库

**`Example`**

```ts
//假设obj为一个数据库对象
const data = obj.getDatabase();
```

#### Returns

[`McDbDatabase`](2d.McDbDatabase.md)

返回数据库

#### Inherited from

[McDbText](2d.McDbText.md).[getDatabase](2d.McDbText.md#getdatabase)

___

### getDatabaseIndexId

▸ **getDatabaseIndexId**(): `number`

获取对象的索引ID

**`Example`**

```ts
//假设obj为一个数据库对象
const id = obj.getDatabaseIndexId();
```

#### Returns

`number`

#### Inherited from

[McDbText](2d.McDbText.md).[getDatabaseIndexId](2d.McDbText.md#getdatabaseindexid)

___

### getExtensionDictionary

▸ **getExtensionDictionary**(): [`McDbDictionary`](2d.McDbDictionary.md)

得到对象的扩展字典数据.

**`Example`**

```ts
//假设obj为一个数据库对象
const id = obj.getOwnerID();
```

#### Returns

[`McDbDictionary`](2d.McDbDictionary.md)

扩展字典数据

#### Inherited from

[McDbText](2d.McDbText.md).[getExtensionDictionary](2d.McDbText.md#getextensiondictionary)

___

### getGripPoints

▸ **getGripPoints**(): [`McGePoint3dArray`](2d.McGePoint3dArray.md)

获取对象的控制点

**`Example`**

```ts
//假设obj为一个数据库对象
const ptArr = obj.getGripPoints();
```

#### Returns

[`McGePoint3dArray`](2d.McGePoint3dArray.md)

#### Inherited from

[McDbText](2d.McDbText.md).[getGripPoints](2d.McDbText.md#getgrippoints)

___

### getHandle

▸ **getHandle**(): `string`

得到对象句柄

**`Example`**

```ts
//假设obj为一个数据库对象
const handle = obj.getHandle();
```

#### Returns

`string`

返回对象句柄

#### Inherited from

[McDbText](2d.McDbText.md).[getHandle](2d.McDbText.md#gethandle)

___

### getImp

▸ **getImp**(): `any`

获取内部实现对象。

**`Example`**

```ts
import { McRxObject } from 'mxcad';

let obj = new McRxObject();
let imp = obj.getImp();
```

#### Returns

`any`

内部实现对象。

#### Inherited from

[McDbText](2d.McDbText.md).[getImp](2d.McDbText.md#getimp)

___

### getJson

▸ **getJson**(): `string`

获取 JSON 格式的字符串。

**`Example`**

```ts
import { McRxObject } from 'mxcad';

let obj = new McRxObject();
const json = obj.getJson()
```

#### Returns

`string`

JSON 格式的字符串。

#### Inherited from

[McDbText](2d.McDbText.md).[getJson](2d.McDbText.md#getjson)

___

### getObjectID

▸ **getObjectID**(): [`McObjectId`](2d.McObjectId.md)

获取对象 ID。

**`Example`**

```ts
import { McDbObject } from "mxcad";
const id = obj.getObjectID();
```

#### Returns

[`McObjectId`](2d.McObjectId.md)

对象 ID。

#### Inherited from

[McDbText](2d.McDbText.md).[getObjectID](2d.McDbText.md#getobjectid)

___

### getOwnerID

▸ **getOwnerID**(): `number`

得到对象拥用者的id

**`Example`**

```ts
//假设obj为一个数据库对象
const id = obj.getOwnerID();
```

#### Returns

`number`

#### Inherited from

[McDbText](2d.McDbText.md).[getOwnerID](2d.McDbText.md#getownerid)

___

### getxData

▸ **getxData**(`appName?`): [`MxCADResbuf`](2d.MxCADResbuf.md)

得到对象的扩展数据

**`Example`**

```ts
// 假设ent为有效实例对象
const xData = ent.getXData();
```

#### Parameters

| Name | Type | Default value | Description |
| :------ | :------ | :------ | :------ |
| `appName` | `string` | `""` | 扩展数据名 |

#### Returns

[`MxCADResbuf`](2d.MxCADResbuf.md)

#### Inherited from

[McDbText](2d.McDbText.md).[getxData](2d.McDbText.md#getxdata)

___

### getxDataDouble

▸ **getxDataDouble**(`appName`): `Object`

获取实体的指定 XData 类型中的 double 值

**`Example`**

```ts
// 假设ent为有效实例对象
let data = ent.getxDataDouble("DataName");
if(data.ret){
  console.log(data.val)
}
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `appName` | `string` | 扩展数据名称 |

#### Returns

`Object`

double 值

| Name | Type |
| :------ | :------ |
| `ret` | `boolean` |
| `val` | `number` |

#### Inherited from

[McDbText](2d.McDbText.md).[getxDataDouble](2d.McDbText.md#getxdatadouble)

___

### getxDataLong

▸ **getxDataLong**(`appName`): `Object`

获取实体的指定 XData 类型中的 long（整数）值

**`Example`**

```ts
// 假设ent为有效实例对象
let data = ent.getxDataLong("DataName");
if(data.ret){
  console.log(data.val)
}
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `appName` | `string` | 扩展数据名称 |

#### Returns

`Object`

long 值

| Name | Type |
| :------ | :------ |
| `ret` | `boolean` |
| `val` | `number` |

#### Inherited from

[McDbText](2d.McDbText.md).[getxDataLong](2d.McDbText.md#getxdatalong)

___

### getxDataPoint

▸ **getxDataPoint**(`appName`): `Object`

获取实体的指定 XData 类型中的点对象

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `appName` | `string` | 扩展数据名称 |

#### Returns

`Object`

获取结果及三维点对象

| Name | Type |
| :------ | :------ |
| `ret` | `boolean` |
| `val` | [`McGePoint3d`](2d.McGePoint3d.md) |

#### Inherited from

[McDbText](2d.McDbText.md).[getxDataPoint](2d.McDbText.md#getxdatapoint)

___

### getxDataString

▸ **getxDataString**(`appName`): `Object`

获取与特定实体关联的 XData 信息，并以字符串形式返回

**`Example`**

```ts
// 假设ent为有效实例对象
let data = ent.getxDataString("DataName");
if(data.ret){
  console.log(data.val)
}
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `appName` | `string` | 扩展数据名称 |

#### Returns

`Object`

val XData信息 | ret 是否返回成功

| Name | Type |
| :------ | :------ |
| `ret` | `boolean` |
| `val` | `string` |

#### Inherited from

[McDbText](2d.McDbText.md).[getxDataString](2d.McDbText.md#getxdatastring)

___

### highlight

▸ **highlight**(`isHighlight`): `void`

设置对象是否高亮

**`Example`**

```ts
import { McDbEntity } from 'mxcad'
const ent = new McDbEntity()
ent.highlight(true);
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `isHighlight` | `boolean` | 是否高亮 |

#### Returns

`void`

#### Inherited from

[McDbText](2d.McDbText.md).[highlight](2d.McDbText.md#highlight)

___

### initTempObject

▸ **initTempObject**(`imp`): `void`

初始化临时对象。

**`Example`**

```ts
import { McRxObject } from 'mxcad';

let obj = new McRxObject();
obj.initTempObject()
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `imp` | `any` | 内部实现对象。 |

#### Returns

`void`

#### Inherited from

[McDbText](2d.McDbText.md).[initTempObject](2d.McDbText.md#inittempobject)

___

### isErased

▸ **isErased**(): `boolean`

对象是否已经删除

**`Example`**

```ts
//假设obj为一个数据库对象
const res = obj.isErased();
console.log(res);
```

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[isErased](2d.McDbText.md#iserased)

___

### isHaveExtensionDictionary

▸ **isHaveExtensionDictionary**(): `boolean`

是否有扩展字典数据.

**`Example`**

```ts
//假设obj为一个数据库对象
const res = obj.isHaveExtensionDictionary();
```

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[isHaveExtensionDictionary](2d.McDbText.md#ishaveextensiondictionary)

___

### isKindOf

▸ **isKindOf**(`sObjectName`): `boolean`

判断对象类型

**`Example`**

```ts
import { McRxObject } from 'mxcad';

let obj = new McRxObject();
let isKind = obj.isKindOf('SomeObjectType');
console.log(isKind); // 输出: true 或 false
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `sObjectName` | `string` | 类型名 |

#### Returns

`boolean`

返回对象是否是目标类型

#### Inherited from

[McDbText](2d.McDbText.md).[isKindOf](2d.McDbText.md#iskindof)

___

### isNull

▸ **isNull**(): `any`

判断是否为空对象

**`Example`**

```ts
import { McRxObject } from 'mxcad';

let obj = new McRxObject();
console.log(obj.isNull()); // 输出: true 或 false
```

#### Returns

`any`

#### Inherited from

[McDbText](2d.McDbText.md).[isNull](2d.McDbText.md#isnull)

___

### mirror

▸ **mirror**(`point1`, `point2`): `boolean`

镜向对象

**`Example`**

```ts
import { McDbEntity, McGePoint3d } from 'mxcad'
const ent = new McDbEntity()
ent.mirror(new McGePoint3d(0,0,0), new McGePoint3d(20,10,0))
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `point1` | [`McGePoint3d`](2d.McGePoint3d.md) | 镜像基点 |
| `point2` | [`McGePoint3d`](2d.McGePoint3d.md) | - |

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[mirror](2d.McDbText.md#mirror)

___

### move

▸ **move**(`fromPoint`, `toPoint`): `boolean`

移动对象

**`Example`**

```ts
import { McDbEntity, McGePoint3d } from 'mxcad'
const ent = new McDbEntity()
ent.move(new McGePoint3d(0,0,0), new McGePoint3d(20,0,0))
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `fromPoint` | [`McGePoint3d`](2d.McGePoint3d.md) | 移动开始点 |
| `toPoint` | [`McGePoint3d`](2d.McGePoint3d.md) | 移动结束点 |

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[move](2d.McDbText.md#move)

___

### moveGripPointsAt

▸ **moveGripPointsAt**(`iIndex`, `dXOffset`, `dYOffset`, `dZOffset`): `any`

移动对象的控制点

**`Example`**

```ts
//假设obj为一个数据库对象
obj.moveGripPointsAt(1,10,10,10);
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `iIndex` | `number` | 索引 |
| `dXOffset` | `number` | X轴偏移量 |
| `dYOffset` | `number` | Y轴偏移量 |
| `dZOffset` | `number` | Z轴偏移量 |

#### Returns

`any`

#### Inherited from

[McDbText](2d.McDbText.md).[moveGripPointsAt](2d.McDbText.md#movegrippointsat)

___

### rotate

▸ **rotate**(`basePoint`, `dRotationAngle`): `boolean`

旋转对象

**`Example`**

```ts
import { McDbEntity, McGePoint3d } from 'mxcad'
const ent = new McDbEntity()
ent.rotate(new McGePoint3d(0,0,0), Math.PI)
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `basePoint` | [`McGePoint3d`](2d.McGePoint3d.md) | 旋转基点 |
| `dRotationAngle` | `number` | 旋转角度 |

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[rotate](2d.McDbText.md#rotate)

___

### scaleEntity

▸ **scaleEntity**(`basePoint`, `dScaleFactor`): `boolean`

缩放对象

**`Example`**

```ts
import { McDbEntity, McGePoint3d } from 'mxcad'
const ent = new McDbEntity()
ent.scaleEntity(new McGePoint3d(0,0,0), 0.5)
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `basePoint` | [`McGePoint3d`](2d.McGePoint3d.md) | 缩放基点 |
| `dScaleFactor` | `number` | 缩放因子（<1 缩小； >1 放大） |

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[scaleEntity](2d.McDbText.md#scaleentity)

___

### setJson

▸ **setJson**(`str`): `boolean`

设置 JSON 格式的字符串。

**`Example`**

```ts
import { McRxObject } from 'mxcad';

let obj = new McRxObject();
const res = obj.setJson('{"key": "value"}');
console.log(res)
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `str` | `string` | JSON 格式的字符串。 |

#### Returns

`boolean`

是否设置成功。

#### Inherited from

[McDbText](2d.McDbText.md).[setJson](2d.McDbText.md#setjson)

___

### setxData

▸ **setxData**(`xdata`): `boolean`

设置对象的扩展数据

**`Example`**

```ts
import { MxCADUiPrEntity, McDbEntity } from "mxcad";

//设置扩展数据
let selEntity = new MxCADUiPrEntity();
selEntity.setMessage("选择对象");
let id = await selEntity.go();
if (!id.isValid()) return;
let ent:McDbEntity = id.getMcDbEntity();
if (ent === null) return;
ent.setxData(new MxCADResbuf([{type:DxfCode.kExDataName,val:"DataName"},{type:DxfCode.kString,val:"yyyyy"}]));
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `xdata` | [`MxCADResbuf`](2d.MxCADResbuf.md) | 扩展数据链表 |

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[setxData](2d.McDbText.md#setxdata)

___

### setxDataDouble

▸ **setxDataDouble**(`appName`, `val`): `boolean`

设置实体的指定 XData 类型中的 double 值

**`Example`**

```ts
import { MxCADUiPrEntity, McDbEntity } from "mxcad";
let selEntity = new MxCADUiPrEntity();
selEntity.setMessage("选择对象");
let id = await selEntity.go();
if (!id.isValid()) return;
let ent:McDbEntity = id.getMcDbEntity();
if (ent === null) return;
const res = ent.setxDataDouble("DataName", 0);
if(res){
  //设置成功
}else{
  //设置失败
}
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `appName` | `string` | 扩展数据名称 |
| `val` | `number` | double 值 |

#### Returns

`boolean`

布尔值

#### Inherited from

[McDbText](2d.McDbText.md).[setxDataDouble](2d.McDbText.md#setxdatadouble)

___

### setxDataLong

▸ **setxDataLong**(`appName`, `val`): `boolean`

设置实体的指定 XData 类型中的 long（整数）值

**`Example`**

```ts
import { MxCADUiPrEntity, McDbEntity } from "mxcad";

let selEntity = new MxCADUiPrEntity();
selEntity.setMessage("选择对象");
let id = await selEntity.go();
if (!id.isValid()) return;
let ent:McDbEntity = id.getMcDbEntity();
if (ent === null) return;
const res = ent.setxDataLong("DataName", 123456);
if(res){
  //设置成功
}else{
  //设置失败
}
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `appName` | `string` | 扩展数据名称 |
| `val` | `number` | long 值 |

#### Returns

`boolean`

long 值

#### Inherited from

[McDbText](2d.McDbText.md).[setxDataLong](2d.McDbText.md#setxdatalong)

___

### setxDataPoint

▸ **setxDataPoint**(`appName`, `val`): `boolean`

设置实体的指定 XData 类型中的点对象

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `appName` | `string` | 扩展数据名称 |
| `val` | [`McGePoint3d`](2d.McGePoint3d.md) | 点对象 |

#### Returns

`boolean`

获取结果及三维点对象

#### Inherited from

[McDbText](2d.McDbText.md).[setxDataPoint](2d.McDbText.md#setxdatapoint)

___

### setxDataString

▸ **setxDataString**(`appName`, `val`): `boolean`

设置与特定实体关联的 XData 信息，并以字符串形式设置

**`Example`**

```ts
import { MxCADUiPrEntity, McDbEntity } from "mxcad";
let selEntity = new MxCADUiPrEntity();
selEntity.setMessage("选择对象");
let id = await selEntity.go();
if (!id.isValid()) return;
let ent:McDbEntity = id.getMcDbEntity();
if (ent === null) return;
const res = ent.setxDataString("DataName", "xxxxx");
if(res){
  //设置成功
}else{
  //设置失败
}
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `appName` | `string` | 扩展数据名称 |
| `val` | `string` | 字符串值 |

#### Returns

`boolean`

是否设置成功

#### Inherited from

[McDbText](2d.McDbText.md).[setxDataString](2d.McDbText.md#setxdatastring)

___

### syncData

▸ **syncData**(`_toCpp?`): `boolean`

同步实体的数据。这个方法可能是在修改了实体的属性或者附加了新的数据之后调用的，以确保所有的改变都被正确地保存到实体的数据库记录中。

**`Example`**

```ts
// 假设ent为有效实例对象
const res = ent.syncData(true);
if(res){
  //同步成功
}else{
  //同步失败
}
```

#### Parameters

| Name | Type | Default value | Description |
| :------ | :------ | :------ | :------ |
| `_toCpp` | `boolean` | `true` | 是否同步数据 |

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[syncData](2d.McDbText.md#syncdata)

___

### transformBy

▸ **transformBy**(`transformationMatrix`): `boolean`

变换对象

**`Example`**

```ts
import { McGeMatrix3d, McDbEntity, McGeVector3d} from 'mxcad'
 const ent = new McDbEntity()
   let matrix = new McGeMatrix3d();
   matrix.setToTranslation(new McGeVector3d(20,0,0));//平移
   ent.transformBy(matrix);
```

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `transformationMatrix` | [`McGeMatrix3d`](2d.McGeMatrix3d.md) | 变换矩阵 |

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[transformBy](2d.McDbText.md#transformby)

___

### unErase

▸ **unErase**(): `boolean`

反删除对象。

**`Example`**

```ts
//假设obj为一个数据库对象
const res = obj.unErase();
console.log(res);
```

#### Returns

`boolean`

#### Inherited from

[McDbText](2d.McDbText.md).[unErase](2d.McDbText.md#unerase)

___

### updateDisplay

▸ **updateDisplay**(): `void`

显示调用对象更新显示.

**`Example`**

```ts
// 假设ent为有效实例对象
ent.updateDisplay()
```

#### Returns

`void`

#### Inherited from

[McDbText](2d.McDbText.md).[updateDisplay](2d.McDbText.md#updatedisplay)
