# Block

We can create a block by instantiating the McDbBlockReference() object. A block is a collection of multiple graphics into an object that can be moved, copied, or inserted into a graph multiple times as a whole. In mxcad can be combined with McDbBlockTableRecord() block record object to create a custom block, A block is defined by setting the block's base point origin, adding block record appendAcDbEntity(), and block position.

Click on the [McDbBlockReference()](../../api/classes/2d.McDbBlockReference.md), [McDbBlockTableRecord()](../../api/classes/2d.McDbBlockTableRecord.md) to check the detailed description attributes and methods.

```ts
import { MxCpp, McDbBlockTableRecord, McDbBlockReference, McDbLine, McCmColor } from "mxcad"

let mxcad = MxCpp.getCurrentMxCAD();
// First get the block table from the database
let blkTable =  mxcad.getDatabase().getBlockTable();
// Adds a new block record to the block table
let blkRecId = blkTable.add(new McDbBlockTableRecord());

// Get the newly added block record again based on ObjectId
let blkTableRecord:McDbBlockTableRecord = blkRecId.getMcDbBlockTableRecord()

// Add two line segments and then the specific properties of each line segment here in the block record, such as the start point and the end point, are assigned to themselves
const line = new McDbLine(80, 80, 0, -80, -80, 0)
line.trueColor = new McCmColor(255, 0, 0)
const line1 = new McDbLine(-80, 80, 0, 80, -80, 0)
blkTableRecord.appendAcDbEntity(line);
blkTableRecord.appendAcDbEntity(line1);

// Set the base point of the block is generally a point in the surrounding box and can be specified arbitrarily
blkTableRecord.origin = new McGePoint3d(0,0,0);

// The instantiation block reference here needs to set the ObjectId we just added to the block record
let blkRef = new McDbBlockReference();
blkRef.blockTableRecordId = blkRecId;
// Finally set the position render block
blkRef.position = new McGePoint3d(0,0,0);

mxcad.drawEntity(blkRef);
```
:::demo
```tsx
import {  McObject, McDbBlockTableRecord, McDbCircle, McDbBlockReference, McDbLine, McGePoint3d, McCmColor } from "mxcad"

export default () => {
    const mxcad = new McObject()
    mxcad.create({
      canvas: "#myCanvas",
      locateFile: (fileName: string)=> {
            // CDN loading must use resources in wasm/ 2D-ST, because github restrictions cannot use wasm/2d resources
            // Use wasm/2d to comply with the browser same-origin policy or use other means to circumvent the browser same-origin policy
            return self.location.origin + "/mxcad_docs/wasm/2d-st/" + fileName
      },
      // The directory location where the font is loaded
      fontspath: self.location.origin + "/mxcad_docs/fonts",
      // Load the converted drawing file
      fileUrl: self.location.origin + "/mxcad_docs/test.mxweb",
      onOpenFileComplete: ()=>{
            // First get the block table from the database
            let blkTable =  mxcad.getDatabase().getBlockTable();
            // Adds a new block record to the block table
            let blkRecId = blkTable.add(new McDbBlockTableRecord());

            // Get the newly added block record again based on ObjectId
            let blkTableRecord:McDbBlockTableRecord = blkRecId.getMcDbBlockTableRecord()

            // Add two line segments and then the specific properties of each line segment here in the block record, such as the start point and the end point, are assigned to themselves
            const line = new McDbLine(50, 50, 0, -50, -50, 0)
            line.trueColor = new McCmColor(0, 255, 0)
            const line1 = new McDbLine(-50, 50, 0, 50, -50, 0)
            const circle = new McDbCircle(0, 0, 0, 50)
            circle.trueColor = new McCmColor(255,255,0)
            blkTableRecord.appendAcDbEntity(line);
            blkTableRecord.appendAcDbEntity(line1);
            blkTableRecord.appendAcDbEntity(circle);

            // Set the base point of the block is generally a point in the surrounding box and can be specified arbitrarily
            blkTableRecord.origin = new McGePoint3d(0,0,0);

            // The instantiation block reference here needs to set the ObjectId we just added to the block record
            let blkRef = new McDbBlockReference();
            blkRef.blockTableRecordId = blkRecId;
            // Finally set the position render block
            blkRef.position = new McGePoint3d(0,0,0);

            mxcad.drawEntity(blkRef);
            
            mxcad.zoomAll()
            mxcad.zoomScale(0.8)
      }
    })
    return (<div style="height: 500px; overflow: hidden;"><canvas id="myCanvas" ></canvas>
    </div>)
}
```
:::